apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  serviceName: "mysql-headless"
  replicas: {{ .Values.statefulset.replicas }}

  selector:
    matchLabels:
      app: mysql
      project: expense
      tier: db

  template:
    metadata:
      labels:
        app: mysql
        project: expense
        tier: db

    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1a   # ✅ correct

      containers:
        - name: mysql
          image: giri1492/mysql:{{ .Values.statefulset.version }}
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: expense-ebs
        resources:
          requests:
            storage: {{ .Values.statefulset.storage }}